#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export VERSION_SCRIPT="import sys; print('%s.%s' % sys.version_info[0:2])"
export PYTHON_VERSION=`${PREFIX}python -c "$VERSION_SCRIPT"`

set -x

${PREFIX}nox -s test-${PYTHON_VERSION}
