resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: florimondmanca/azure-pipelines-templates
      ref: refs/tags/4.0

trigger:
  - master
  - refs/tags/*

pr:
  - master

variables:
  - name: CI
    value: true
  - name: PIP_CACHE_DIR
    value: $(Pipeline.Workspace)/.cache/pip
  - group: pypi-credentials

stages:
  - stage: test
    jobs:
      - template: job--python-check.yml@templates
        parameters:
          pythonVersion: "3.8"
      - template: job--python-test.yml@templates
        parameters:
          jobs:
            py37:
            py38:
              coverage: true
            py39:
            py310:

  - stage: publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - template: job--python-publish.yml@templates
        parameters:
          token: $(pypiToken)
          pythonVersion: "3.8"
